AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'namespace', 'factory', 'define', 'configure', 'trait', 'after']

Metrics/LineLength:
  Max: 130

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
